language: python
python:
  - "3.5"

sudo: true

branches:
  only:
    - master
    - develop

before_install: travis_retry pip install -U pip

install: travis_retry pip install tox-travis

before_script:
  - echo "#!/bin/sh" > emit
  - sudo cp -f emit /usr/local/bin/.
  - sudo chmod +x /usr/local/bin/emit

script: tox
